version: '3'
services:
  cms:
    image: ghost:2.4-alpine
    container_name: stuffs.cool
    volumes:
      - ./content:/var/lib/ghost/content
    ports:
      - "2360:2368"
    environment :
      NODE_ENV: development
      url: http://d-14:2360

  # cms:
  #   image: ghost:1-alpine
  #   container_name: stuffs.cool.v1
  #   volumes:
  #     - ./content:/var/lib/ghost/content
  #   ports:
  #     - "2361:2368"
  #   environment :
  #     NODE_ENV: development
  #     url: http://d-14:2361
